### ISSUE TITLE
[MIG-666]  Change wording of "halt transactions" to be meaningful to kube admins

### ISSUE THREAD

**Issue by djwhatle** [konveyor/mig-ui#1207]
Currently when you're about to run a migration, you're given an option to "halt transactions", which is vague and has caused user confusion several times. 

![image](https://user-images.githubusercontent.com/7576968/118004748-b9ef0080-b317-11eb-8649-b4132bbb5156.png)

Users need to know _exactly_ what will happen to their important Pods and data when this option is selected. The existing wording doesn't map to any k8s mechanisms, so let's make it more explicit.

Based on feedback from the team, telling the user that "Pods will be scaled to zero replicas" might be the most succinct way we can represent this. 

We could also choose to take a more detail heavy approach outlining what we do for each resource kind, since quiesce takes different actions on each resource kind.

_Examples of this nuance from [quiesce.go](https://github.com/konveyor/mig-controller/blob/master/pkg/controller/migmigration/quiesce.go)_
 - `Kind: Deployment, StatefulSet, ReplicaSet, DeploymentConfig` 
   - Replica count is set to 0
   - Original Replica count is stored in an annotation
   - Original Replica count is restored on target after PV data has been migrated

 - `Kind: DaemonSet` 
   - Invalid NodeSelector is attached so that DaemonSet Pods becomes unschedulable and stop.
   - Original NodeSelector is stored in an annotation.
   - Original NodeSelector is restored on target after PV data has been migrated

 - `Kind: CronJob` 
   - Spec.Suspend is set to true
   - Original Spec.Suspend value is stored in annotation
   - Original Spec.Suspend value is restored after PV data has been migrated

 - `Kind: Job` 
   - Spec.Parallelism is set to 0
   - Original Spec.Parallelism is stored in annotation
   - Original Spec.Parallelism is restored after PV data has been migrated

**Comment by djwhatle** [comment]
@vconzola do you have any opinions from a UX perspective on how to communicate this info to users? The more verbose set of info on this could be genuinely useful in some cases where the user _needs_ to know the impact of hitting the quiesce button on a production workload, but it's perhaps a lot of info to communicate in a modal.

We do have a more verbose "Rollback" modal and I think that works well though. Maybe it would be OK. Here's how rollback modal looks.

![image](https://user-images.githubusercontent.com/7576968/118007570-400c4680-b31a-11eb-8994-ab97f8253276.png)

**Comment by vconzola** [comment]
@djwhatle One problem with putting so much detailed information in the modal is that the user has no way to refer back to it once the modal is closed. I'd prefer to keep one or two of the most important points in the modal and refer the user to documentation for the details. There's a subtle difference between this case and the rollback case (whose modal also includes too many details, imho). That is that with rollback we're confirming the user's choice to take an action (rollback), whereas forthe migrate case the migration is going to happen in either case - it's more of letting the user choose how it's going to happen. 

So I suggest changing the modal text to "By default, the Migrate process scales all pods in the source namespaces to zero replicas before the migration begins. Persistent volumes associated with the namespaces being migrated are moved or copied to the target cluster as specified in the migration plan.

See the product documentation for a full description of the migrate process."

The checkbox (selected by default) label would be " Scale all source namespace pods to zero replicas before migrating"

I'd like to get @apinnick's thoughts on this too.

**Comment by sseago** [comment]
@vconzola @djwhatle I think the key here is to change the "transactions" wording to something that makes it clear to the user that "pods will be shut down". If we want to relegate the long explanation to the docs, it may be sufficient to simply suggest that user application pods will be shut down prior to volume migration and will not be restarted.

**Comment by apinnick** [comment]
+1 @sseago  I agree that "transactions" is vague. "Pods will be shut down" is much clearer and shorter. User might actually read it.
+1 @vconzola  I agree with your assessment that the user has no way to refer back to the details. Docs would be a better place for details

Re: Migrate vs Rollback modals. I don't think the user approaches these modals in quite the same way, so it may not be accurate to compare them. The user reaches the Migrate modal after creating a migration plan, so there is a temptation to keep clicking ("Yeah, I want to get things going!" click, click, click). However, the user reaches the Rollback modal while testing it, to see how it works, or in order to roll back a migration that did not go well. I think that a user is more willing to read a longer text while rolling back (backing up the car) than when starting a migration (stepping on the gas).

Re: shut down vs scale to 0 replicas. It's better to focus on the end result rather than the means. The user needs to know that the pods are not going to run during the migration. We can add info about scaling down the pods in the documentation, if you think it is necessary. I don't think that the information is all that helpful in a modal.

Here's my suggestion:

Pods on the source cluster will be shut down during migration. Persistent volumes will be moved or copied to the target cluster.

[checkbox] Shut down pods on the source cluster during migration.

**Comment by sseago** [comment]
@apinnick A minor concern with your suggested wording is that I think we should only mention pod shutdown next to the checkbox -- to make it clear that source cluster pods will only be shut down if the (selected-by-default) checkbox is selected.

**Comment by apinnick** [comment]
@sseago Would this work? I'm not sure it's any clearer than my earlier version.

By default, the pods on the source cluster are scaled to zero before migration. Persistent volumes are then moved or copied to the target cluster. See the product documentation<link to MTC doc splash page> for more information.

[checkbox] Shut down the pods on the source cluster before migration.

**Comment by sseago** [comment]
@apinnick Yes, that works for me. Also, "By default, the pods on the source cluster are shut down before migration" would be fine as well. I don't have a strong preference between the two.
