### ISSUE TITLE
No error message shown when fetching resources fails

### ISSUE THREAD

**Issue by ibolton336** [konveyor/mig-ui#689]
<img width="1438" alt="Screen Shot 2020-02-20 at 12 20 32 PM" src="https://user-images.githubusercontent.com/11218376/74961104-8571ea80-53db-11ea-9834-295fb3ea5460.png">

When a session token (https://docs.openshift.com/container-platform/3.3/rest_api/index.html#rest-api-session-tokens) is expired, there is no visual indicator that this has occurred. The fetch polls for resources fail silently in the background and nothing is communicated to the user. This scenario also applies when resource fetch fails for any reason. I turned off my wifi to simulate a loss of connection and this was the result:

<img width="1440" alt="Screen Shot 2020-02-21 at 11 07 18 AM" src="https://user-images.githubusercontent.com/11218376/75052540-c6cace80-549d-11ea-8d4e-44c275438c61.png">

**Comment by vconzola** [comment]
@ibolton336  The issue description says, "When a session token is expired, there is visual indicator that this has occurred."  Is it supposed to say, "...there is **_no_** visual indicator..."? If so, I need some more background. How does the UI behave when the session token has expired? Sounds like it's frozen if fetch polls fail silently. Does that mean navigation is frozen too? Also, what is the corrective action a user needs to do - login to OCP again?

I'm thinking we should display a persistent toast notification explaining the error and redirecting (or linking) the user back to the OCP login page. But I don't know what's possible without better understanding what happens when the session token expires.

**Comment by ibolton336** [comment]
Hey @vconzola  oops yeah that was a typo. No visual indicator is shown. The session token expires after 24 hours.

**Comment by vconzola** [comment]
@ibolton336 After reading through the PF documentation, this situation calls for a modal dialog error. Mockup below.
![session token error](https://user-images.githubusercontent.com/22823035/75061905-aefc4600-54af-11ea-87f7-947abf14b07a.png)
The Try again button should be primary; Cancel should be secondary. Let me know if you need details on any of the other PF components. Example here: https://www.patternfly.org/v4/design-guidelines/usage-and-behavior/modal#report-errors

**Comment by eriknelson** [comment]
It's possible that this is a regression. I had code that should redirect you to the oauth page to get a refreshed token at the client layer. Need to look into this.

**Comment by ibolton336** [comment]
@eriknelson i have seen the error occur only when the token expires and there is still a current user local storage token existing within the users browser. It’s a tough one to reproduce. A similar but separate issue is the lack error shown when the fetches fail for other connectivity reasons non auth related.

**Comment by ibolton336** [comment]
![image](https://user-images.githubusercontent.com/11218376/76242424-197de780-620d-11ea-82ee-ace822bad4c9.png)

This is the edge case when a user has a stale token & tries to log into the UI

**Comment by ibolton336** [comment]
#685
